version: '3'

services:
  database: 
    image: postgres:15.3
    container_name: todo-database
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/postgres:/var/lib/postgresql/data